import mongoose from 'mongoose';


const issueSchema = new mongoose.Schema(
  {
    project: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Project',
      required: true,
    },
    reportedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    description: {
      type: String,
      required: [true, 'Issue description is required'],
      trim: true,
    },
    // Stored as URLs (e.g. uploaded to S3/Cloudinary)
    screenshots: [
      {
        type: String,
        trim: true,
      },
    ],
    // Generated by Mistral AI via LangChain
    aiSummary: {
      type: String,
      default: null,
    },
    aiSummaryGeneratedAt: {
      type: Date,
      default: null,
    },
    status: {
      type: String,
      enum: ['open', 'in_progress', 'resolved'],
      default: 'open',
    },
  },
  { timestamps: true }
);

// Fetch all issues for a project quickly
issueSchema.index({ project: 1, createdAt: -1 });
// Fetch all issues filed by a specific employee
issueSchema.index({ reportedBy: 1 });

export default mongoose.model('Issue', issueSchema);